### ISSUE TITLE
List of Available configurations

### ISSUE THREAD

**Issue by sylvan-d-ash** [webburza/sylius-article-bundle#19]
Hey, I've been looking for a way to change the number of maximum items per page. A list of available configurations would be nice...

**Comment by ychanan** [comment]
Hi @winter7621,

You can get a list of all available options using the built-in Symfony command:

```
app/console config:dump-reference WebburzaSyliusArticleBundle
```

Which is also listed in our [readme](https://github.com/webburza/sylius-article-bundle/blob/master/README.md):

```
webburza_sylius_article:
    file_browser:
        browse_url: "/browser/browse.php"
        upload_url: "/uploader/upload.php"
```

We don't currently have a configuration option for items-per-page, but will definitely add it in the next release. In the meantime, should you make the changes yourself, be sure to let us know via PR.

Tnx,
Y.
